language: cpp
dist: bionic
compiler:
  - clang
os:
  - linux
notifications:
  email: false
before_install:
  - echo $LANG
  - echo $LC_ALL
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make test
